#!/bin/bash

. /etc/krapctl/environment

cp -R ./modules/* "${KRAPCTL_MODULES}"

mkdir -p /etc/k3d/setup

cp ./etc/k3d/setup/calico.yaml /etc/k3d/setup/calico.yaml

cat <<EOF > /etc/k3d/setup/environment
HOSTVOLUMEPATH="${HOSTVOLUMEPATH}"
SECRETSPATH="${SECRETSPATH}"
INSTALLCALICO="${INSTALLCALICO}"
CLUSTERNAME="${CLUSTERNAME}"
DISABLETRAEFIK="${DISABLETRAEFIK}"
DISABLEFLANNEL="${DISABLEFLANNEL}"
DISABLELOADBALANCER="${DISABLELOADBALANCER}"
BASE_PATH="${BASE_PATH}"
REGISTRY_PORT="${REGISTRYPORT}"
REGISTRY_NAME="k3d-${CLUSTERNAME}-registry.local"
EOF

exit 0