name: Deploy DevContainer Features

on:
  push:
    branches: 
      - "main"

  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v3      

    - name: "Publish Features"
      uses: devcontainers/action@v1
      with:
        publish-features: "true"
        base-path-to-features: "./src"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}